### ISSUE TITLE
Cannot save wav file

### ISSUE THREAD

**Issue by hellocatfood** [belangeo/soundgrain#27]
I'm trying to save a wav from soundgrain but when I click on the Start button in the Record Settings section nothing happens. In the terminal I get the following output:
```
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hellocatfood/Desktop/soundgrain/Resources/ControlPanel.py", line 695, in handleRecord
    self.parent.sg_audio.recStart(filename, self.fileformat, self.sampletype)
  File "/home/hellocatfood/Desktop/soundgrain/Resources/audio.py", line 304, in recStart
    self.server.recstart(complete_filename)
  File "/usr/lib/python3/dist-packages/pyo/lib/server.py", line 970, in recstart
    self._server.recstart(stringencode(filename))
SystemError: <method 'recstart' of '_pyo.Server' objects> returned a result with an exception set
```
I'm using Python 3.10.4 on Ubuntu 22.04

**Comment by belangeo** [comment]
Hi, it's already fixed in pyo's sources. You just have to recompile pyo from the latest master.

**Comment by hellocatfood** [comment]
Thanks!
